events { worker_connections 1024; }

http {
  upstream frontend    { server frontend:80; }
  upstream node-api    { server backend-node:5000; }
  upstream python-api  { server backend-python:8000; }
  upstream java-api    { server backend-java:8080; }

  server {
    listen 80;
    server_name _;

    # Frontend
    location / {
      proxy_pass http://frontend;
      proxy_set_header Host ;
      proxy_set_header X-Real-IP ;
    }

    # Node.js API
    location /api/ {
      proxy_pass http://node-api/;
      proxy_set_header Host ;
      proxy_set_header X-Real-IP ;
    }

    # Python FastAPI
    location /py/ {
      proxy_pass http://python-api/;
      proxy_set_header Host ;
      proxy_set_header X-Real-IP ;
    }

    # Java Spring Boot
    location /java/ {
      proxy_pass http://java-api/;
      proxy_set_header Host ;
      proxy_set_header X-Real-IP ;
    }
  }
}
